"""Assemble the UNIFIED District / Customer Studio share file.

The real app's "customer" view is BOTH surfaces, switchable via the "Previewing as"
role selector:
  • CN Director → My Team (district training-supervisor / admin view)
  • Cashier     → Learn   (learner view: gated lessons, quizzes, gated certificate)

This build reuses the proven cashier-studio seed + interactive backend shim (so the
LEARNER half is fully real), then layers in the CN Director's real roster + assigned
track (so the ADMIN half is fully real). One file, no server, both halves first-class.

Rebuild:
    python demo_app.py                                  # :8001 (real backend)
    python share/_capture/capture_api.py                # learner (cashier/trainer) captures
    python share/_capture/capture_director.py           # CN Director captures
    python share/build_share_studio.py                  # -> share/district-admin-studio.html
"""
import json, os, re
import build_share  # reuse the cashier seed builder + constants

ROOT = build_share.ROOT
SHARE = build_share.SHARE
CAP = build_share.CAP
SHIM = build_share.SHIM
INDEX = build_share.INDEX
OUT = os.path.join(SHARE, "district-admin-studio.html")


def _director_by_path():
    with open(os.path.join(CAP, "captures_director.json"), encoding="utf-8") as f:
        caps = json.load(f)
    by = {}
    for c in caps.values():
        if c.get("status") != 200 or not c.get("body"):
            continue
        path = (c.get("path") or "").split("?")[0]
        if not path:
            continue
        try:
            by[path] = json.loads(c["body"])
        except Exception:
            pass
    return by


def build_seed():
    seed = build_share.build_seed()          # cashier learner seed (track/courses/quizzes/assessment/icn/...)
    d = _director_by_path()

    tracks_resp = d.get("/api/tracks", {})
    director_tracks = tracks_resp.get("tracks", []) if isinstance(tracks_resp, dict) else []
    # multi-track seed: cashier learner track + the director's real assigned track(s).
    # matchRole() in the shim routes each persona to the right one.
    seed["tracks"] = [seed["track"]] + [t for t in director_tracks if t.get("id") != seed["track"].get("id")]

    seed["roster"] = d.get("/api/roster", {"districts": [], "roster": []})
    seed["rosterByTrack"] = {p.split("/api/roster/")[1]: b
                             for p, b in d.items()
                             if re.match(r"^/api/roster/[^/]+$", p)}
    seed["regulatoryDates"] = d.get("/api/regulatory-dates", {"deadlines": [], "total": 0})

    # full real catalog (141 modules) for the Library/Catalog tab — richer than the icn-only stub
    if d.get("/api/modules"):
        seed["modules"] = d["/api/modules"]

    # persona-aware What's-new so the learner view never shows "New for CN Director"
    seed["whatsNewByPersona"] = {
        "john-cashier": seed.get("whatsNew", {"items": []}),
        "dana-director": d.get("/api/whats-new", seed.get("whatsNew", {"items": []})),
    }

    if not seed["roster"].get("roster"):
        raise SystemExit("director roster empty — run capture_director.py against a live :8001")
    return seed


# director routes injected at the TOP of the shim's route() so they take precedence
_DIRECTOR_ROUTES = """
    /* ---- District/Customer Studio: CN Director My Team + compliance (persona-aware) ---- */
    if (path === "/api/roster" && method === "GET" && SEED.roster) return SEED.roster;
    var _rtm = path.match(/^\\/api\\/roster\\/([^/]+)$/);
    if (_rtm && method === "GET") { var _rb = (SEED.rosterByTrack || {})[decodeURIComponent(_rtm[1])]; if (_rb) return _rb; }
    if (/^\\/api\\/roster\\/[^/]+\\/nudge-all-overdue$/.test(path) && method === "POST") return { ok: true, count: 0, message: "Reminders logged \\u2014 delivery requires live roster sync (offline preview)." };
    if (/^\\/api\\/roster\\/[^/]+\\/nudge$/.test(path) && method === "POST") { var _n = (body && body.user_ids) ? body.user_ids.length : 1; return { ok: true, count: _n, message: "Reminder logged for " + _n + " staff \\u2014 delivery requires live roster sync (offline preview)." }; }
    if (/^\\/api\\/roster\\/[^/]+\\/report/.test(path)) return HTML("<!doctype html><meta charset=utf-8><body style='font-family:sans-serif;padding:40px;color:#14201A;max-width:640px;margin:auto'><h2>Compliance report</h2><p>The printable PDF is generated by the server and isn't available in this self-contained preview.</p></body>");
    if (path.indexOf("/api/regulatory-dates") === 0) return SEED.regulatoryDates || { deadlines: [], total: 0 };
    if (path.indexOf("/api/whats-new") === 0 && SEED.whatsNewByPersona) return SEED.whatsNewByPersona[persona] || SEED.whatsNewByPersona["john-cashier"] || SEED.whatsNew || { items: [] };
"""


def patch_shim_head(src):
    # 1) multi-track support
    before = "  function allTracks() { return [SEED.track].concat(store.userTracks || []); }"
    after = "  function allTracks() { return (SEED.tracks || [SEED.track]).concat(store.userTracks || []); }"
    if before not in src:
        raise SystemExit("shim_head allTracks() anchor not found — cashier shim changed")
    src = src.replace(before, after)
    # 2) inject director routes at the top of route()
    anchor = "  function route(path, method, persona, body, query) {"
    if anchor not in src:
        raise SystemExit("shim_head route() anchor not found — cashier shim changed")
    src = src.replace(anchor, anchor + "\n" + _DIRECTOR_ROUTES)
    return src


def main():
    seed = build_seed()
    seed_json = json.dumps(seed, ensure_ascii=False)
    seed_json = re.sub(r"</(script)", r"<\\/\1", seed_json, flags=re.I)

    with open(os.path.join(SHIM, "shim_head.js"), encoding="utf-8") as f:
        block_a = patch_shim_head(f.read()).replace("__SEED__", seed_json)
    with open(os.path.join(SHIM, "shim_tail_studio.js"), encoding="utf-8") as f:
        block_b = f.read()
    with open(INDEX, encoding="utf-8") as f:
        html = f.read()

    marker = "\n<script>\n"
    idx = html.find(marker)
    if idx < 0:
        raise SystemExit("could not find main <script> open marker")
    inject_at = idx + len(marker)
    html = html[:inject_at] + "\n/* ===== District/Customer Studio: standalone backend shim (injected) ===== */\n" + block_a + "\n" + html[inject_at:]

    close_idx = html.rfind("</script>")
    html = html[:close_idx] + "\n/* ===== District/Customer Studio: standalone UI layer (injected) ===== */\n" + block_b + "\n" + html[close_idx:]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print("Wrote", OUT)
    print("  size:", round(len(html) / 1024), "KB | seed:", round(len(seed_json) / 1024), "KB")
    print("  tracks:", [t.get("title") for t in seed["tracks"]])
    print("  roster rows:", len(seed["roster"].get("roster", [])),
          "| rosterByTrack:", list(seed["rosterByTrack"].keys()),
          "| modules:", seed["modules"].get("total", 0))


if __name__ == "__main__":
    main()
