"""Prefetch every ticket the mapper touched into one tier-labeled evidence cache.

Run once after Task 1. Produces a single markdown file where each ticket's
Acceptance Criteria (TIER 1) and Description (TIER 3) are explicitly separated —
this is the shared ground truth the SME, Writer, and Reviewer read, and the
structural reason a Description-tier quote can't be mislabeled as `AC:`.

    .venv/Scripts/python.exe prefetch_tickets.py <out_path>
"""
import asyncio
import sys

import tools_sdk

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# Mapper "Tickets Touched" + permission/config tickets the long-form Roles
# section reaches for (NXT-53316 and its epic NXT-38086), plus Item card stories.
KEYS = [
    # epics
    "NXT-45562", "NXT-36067", "NXT-30027", "NXT-26823", "NXT-29833",
    "NXT-40487", "NXT-40775", "NXT-51260", "NXT-13780", "NXT-37500",
    "NXT-38086",
    # stories
    "NXT-37441", "NXT-37110", "NXT-35898", "NXT-33518", "NXT-37568",
    "NXT-37109", "NXT-37111", "NXT-40778", "NXT-54229", "NXT-53530",
    "NXT-37068", "NXT-37815", "NXT-41273", "NXT-43239", "NXT-47249",
    "NXT-30100", "NXT-30102", "NXT-30103", "NXT-24128", "NXT-41275",
    "NXT-37216", "NXT-39594", "NXT-39663", "NXT-40447", "NXT-36583",
    "NXT-36742", "NXT-30155", "NXT-58442", "NXT-40479", "NXT-30036",
    "NXT-30037", "NXT-53316",
]


async def fetch_one(key: str) -> str:
    try:
        r = await tools_sdk.read_ticket.handler({"issue_key": key})
        return r["content"][0]["text"]
    except Exception as e:  # keep going — one bad key shouldn't abort the cache
        return f"{key} | ERROR fetching: {e}"


async def main(out_path: str):
    blocks = []
    for key in KEYS:
        text = await fetch_one(key)
        blocks.append(f"================ {key} ================\n{text}")
        print(f"fetched {key} ({len(text)} chars)")
    header = (
        "# Tier-Labeled Ticket Evidence Cache — Item Management\n"
        "# Generated by prefetch_tickets.py from live NXT Jira.\n"
        "# CITATION RULE: quote ONLY from the '## Acceptance Criteria [TIER 1]' or\n"
        "# '## Release Notes [TIER 1]' blocks when writing `<!-- Source: NXT-#### AC: \"...\" -->`.\n"
        "# Text under '## Description [TIER 3]' is lowest-trust and MUST NEVER be cited as AC.\n"
        f"# Tickets: {len(KEYS)}\n\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n".join(blocks) + "\n")
    print(f"\nWROTE {out_path} ({len(KEYS)} tickets)")


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "tickets-cache.md"
    asyncio.run(main(out))
