"""Inline EVERY cataloged Eligibility guide markdown into resource-center-v2.html.
Reads catalog/resources.json so it stays in sync with whatever is published.
Customer-facing cleanup (stripping frontmatter, NXT-#### refs, Source sections,
page-N artifacts) is done at render-time in v2's JS — not here — so this script
stays a thin pipeline. Re-run after editing any cataloged guide.
"""
from pathlib import Path
import json
import re

ROOT = Path(r'C:\Users\rahul.mehta\Downloads\Financials-Documentation-KT\jira-brain')
HTML = ROOT / 'wiki' / 'training' / 'resource-center-v2.html'
CATALOG = ROOT / 'catalog' / 'resources.json'

catalog = json.loads(CATALOG.read_text(encoding='utf-8'))
resources = catalog['resources']

blocks = []
missing = []
for r in resources:
    rid = r['id']
    rel_path = r.get('path')
    if not rel_path:
        missing.append((rid, 'no path'))
        continue
    p = ROOT / rel_path
    if not p.exists():
        missing.append((rid, f'missing file: {rel_path}'))
        continue
    body = p.read_text(encoding='utf-8')
    # Defang any literal </script> inside the markdown so the wrapper survives.
    body = body.replace('</script>', r'<\/script>')
    blocks.append(f'<script type="text/markdown" id="md-{rid}">\n{body}\n</script>')

if missing:
    print('Skipped:')
    for rid, why in missing:
        print(f'  {rid}: {why}')

embed = (
    '<!-- ====== INLINE_GUIDES_START — generated by _embed_v2.py ====== -->\n'
    + '\n'.join(blocks)
    + '\n<!-- ====== INLINE_GUIDES_END ====== -->'
)

html = HTML.read_text(encoding='utf-8')

# Idempotent — remove any prior block between the markers, then re-insert.
html = re.sub(
    r'<!-- ====== INLINE_GUIDES_START.*?INLINE_GUIDES_END ====== -->',
    '', html, count=1, flags=re.DOTALL,
)

# Insert immediately before the <script type="application/json" id="catalog-data"> anchor.
anchor = '<!-- ========== DATA ========== -->'
if anchor not in html:
    raise SystemExit(f'anchor "{anchor}" not found in v2 HTML')
html = html.replace(anchor, embed + '\n\n' + anchor, 1)

HTML.write_text(html, encoding='utf-8')
print(f'Embedded {len(blocks)} markdown blocks. New v2 HTML size: {len(html):,} bytes.')
